version: "3.8"
services:
  bashls:
    image: lspcontainers/bash-language-server:${bashls}
    build:
      context: servers/bashls
      args:
        VERSION: ${bashls}

  clangd:
    image: lspcontainers/clangd-language-server:${clangd}
    build:
      context: servers/clangd
      args:
        VERSION: ${clangd}

  dockerls:
    image: lspcontainers/docker-language-server:${dockerls}
    build:
      context: servers/dockerls
      args:
        VERSION: ${dockerls}

  gopls:
    image: lspcontainers/gopls:${gopls}
    build:
      context: servers/gopls
      args:
        VERSION: ${gopls}

  html:
    image: lspcontainers/html-language-server:${html}
    build:
      context: servers/html
      args:
        VERSION: ${html}

  intelephense:
    image: lspcontainers/intelephense:${intelephense}
    build:
      context: servers/intelephense
      args:
        VERSION: ${intelephense}

  jsonls:
    image: lspcontainers/json-language-server:${jsonls}
    build:
      context: servers/jsonls
      args:
        VERSION: ${jsonls}

  omnisharp:
    image: lspcontainers/csharp-language-server:${omnisharp}
    build:
      context: servers/omnisharp
      args:
        VERSION: ${omnisharp}

  pylsp:
    image: lspcontainers/python-lsp-server:${pylsp}
    build:
      context: servers/pylsp
      args:
        VERSION: ${pylsp}

  pyright:
    image: lspcontainers/pyright-langserver:${pyright}
    build:
      context: servers/pyright
      args:
        VERSION: ${pyright}

  rust_analyzer:
    image: lspcontainers/rust-analyzer:${rust_analyzer}
    build:
      context: servers/rust_analyzer
      args:
        VERSION: ${rust_analyzer}

  sumneko_lua:
    image: lspcontainers/lua-language-server:${sumneko_lua}
    build:
      context: servers/sumneko_lua
      args:
        VERSION: ${sumneko_lua}

  svelteserver:
    image: lspcontainers/svelte-language-server:${svelteserver}
    build:
      context: servers/svelteserver
      args:
        VERSION: ${svelteserver}

  terraformls:
    image: lspcontainers/terraform-ls:${terraformls}
    build:
      context: servers/terraformls
      args:
        VERSION: ${terraformls}

  tsserver:
    image: lspcontainers/typescript-language-server:${tsserver}
    build:
      context: servers/tsserver
      args:
        VERSION: ${tsserver}

  yamlls:
    image: lspcontainers/yaml-language-server:${yamlls}
    build:
      context: servers/yamlls
      args:
        VERSION: ${yamlls}

  vuels:
    image: lspcontainers/vue-language-server:${vuels}
    build:
      context: servers/vuels
      args:
        VERSION: ${vuels}
