name: Push LSP Docker Images

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build_and_push:
    name: Build and push ${{ matrix.context }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - context: bashls
            tag: bash-language-server
            version: 1.17.0

          - context: clangd
            tag: clangd-language-server
            version: 11.1.0

          - context: dockerls
            tag: docker-language-server
            version: 0.4.1

          - context: gopls
            tag: gopls
            version: 0.6.11

          - context: html
            tag: html-language-server
            version: 1.4.0

          - context: jsonls
            tag: json-language-server
            version: 1.3.4

          - context: pylsp
            tag: python-lsp-server
            version: 1.1.0

          - context: pyright
            tag: pyright-langserver
            version: 1.1.137

          - context: rust_analyzer
            tag: rust-analyzer
            version: "2021-05-03"

          - context: sumneko_lua
            tag: lua-language-server
            version: 1.21.1

          - context: svelteserver
            tag: svelte-language-server
            version: 0.14.3

          - context: terraformls
            tag: terraform-ls
            version: 0.20.1

          - context: tsserver
            tag: typescript-language-server
            version: 0.5.1

          - context: vuels
            tag: vue-language-server
            version: 0.7.2

          - context: yamlls
            tag: yaml-language-server
            version: 0.18.0

          - context: intelephense
            tag: intelephense
            version: 1.7.1

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      # TODO: Replace w/ Github Action - https://github.com/lspcontainers/dockerfiles/runs/2724936969?check_suite_focus=true#step:4:7
      - name: Run hadolint
        run: >
          docker container run
          --entrypoint hadolint
          --rm
          --volume $(pwd):/code
          --workdir /code
          hadolint/hadolint:2.4.1-alpine
          servers/${{ matrix.context }}/Dockerfile

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: ${{ github.ref == 'refs/heads/main' }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VERSION=${{ matrix.version }}
          context: servers/${{ matrix.context }}
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: lspcontainers/${{ matrix.tag }}:${{ matrix.version }},lspcontainers/${{ matrix.tag }}:latest
